
common:
  data: /home/minjae/ws/data/nvGesture/Video_data
  splits: /home/minjae/ws/data/nvGesture/Video_data

  #-------basic Hyparameter----------
  visdom:
    enable: False
    visname: NvGesture

  dataset: NvGesture #Database name e.g., NTU, THUREAD ...
  batch_size: 1
  test_batch_size: 1
  num_workers: 5
  learning_rate: 0.01
  learning_rate_min: 0.00001
  momentum: 0.9
  weight_decay: 0.0003
  init_epochs: 0
  epochs: 100
  report_freq: 10 # unknown
  optim: SGD
  dist: False
  vis_feature: True # Visualization?
  DEBUG: False

  scheduler:
    name: cosin
    patience: 4
    warm_up_epochs: 3
  loss:
    name: CE
    labelsmooth: True
  MultiLoss: True
  loss_lamdb: [ 1, 0.5, 0.5, 0.5 ]
  distill: 1.
model:
  Network: I3DWTrans # e.g., I3DWTrans or FusionNet
  pretrained: /home/minjae/ws/MotionRGBD/Checkpoints/I3DWTrans-NvGesture-M-20240418-162142/checkpoint.pth.tar
  resumelr: True
  sample_duration: 64
  sample_size: 224
  grad_clip: 5.
  SYNC_BN: 1
  w: 4 # 4 is best for Nv
  temper: 0.4
  recoupling: True
  knn_attention: 0.7
  sharpness: True
  temp: [ 0.04, 0.07 ]
  frp: True
  SEHeads: 1
  N: 6 # Number of Transformer Blocks
  rgb_checkpoint: /home/minjae/ws/MotionRGBD/Checkpoints/I3DWTrans-NvGesture-M-20240418-162142/checkpoint.pth.tar
  #-------Used for fusion network----------

dataset:
  type: M
  flip: 0.0
  rotated: 0.5
  angle: (-10, 10)
  Blur: False
  resize: (256, 256)
  crop_size: 224
  low_frames: 16
  media_frames: 32
  high_frames: 48

# I3DWTrans-NvGesture-K-20221017-113943 90.83
# I3DWTrans-NvGesture-M-20221018-123442 88.75
