wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.16.6
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715907854.0
    t:
      1:
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 1
      - 23
      4: 3.9.19
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
    framework: torch
config:
  desc: null
  value: config/NvGesture_init.yml
eval_only:
  desc: null
  value: false
local_rank:
  desc: null
  value: 0
nprocs:
  desc: null
  value: 1
save_grid_image:
  desc: null
  value: false
save_output:
  desc: null
  value: false
demo_dir:
  desc: null
  value: ./demo
resume:
  desc: null
  value: ''
distill_lamdb:
  desc: null
  value: 0.0
drop_path_prob:
  desc: null
  value: 0.5
save:
  desc: null
  value: Checkpoints/I3DWTrans-NvGesture-M-20240517-100420
seed:
  desc: null
  value: 123
data:
  desc: null
  value: /home/minjae/ws/data/nvGesture/Video_data/rgb
splits:
  desc: null
  value: /home/minjae/ws/data/nvGesture/Video_data/rgb
visdom:
  desc: null
  value:
    enable: false
    visname: NvGesture
dataset:
  desc: null
  value: NvGesture
batch_size:
  desc: null
  value: 1
test_batch_size:
  desc: null
  value: 1
num_workers:
  desc: null
  value: 8
learning_rate:
  desc: null
  value: 0.005
learning_rate_min:
  desc: null
  value: 1.0e-05
momentum:
  desc: null
  value: 0.9
weight_decay:
  desc: null
  value: 0.0003
init_epochs:
  desc: null
  value: 0
epochs:
  desc: null
  value: 100
report_freq:
  desc: null
  value: 100
optim:
  desc: null
  value: SGD
dist:
  desc: null
  value: false
vis_feature:
  desc: null
  value: true
DEBUG:
  desc: null
  value: false
scheduler:
  desc: null
  value:
    name: cosin
    patience: 4
    warm_up_epochs: 3
loss:
  desc: null
  value:
    name: CE
    labelsmooth: true
MultiLoss:
  desc: null
  value: true
loss_lamdb:
  desc: null
  value:
  - 1
  - 0.5
  - 0.5
  - 0.5
distill:
  desc: null
  value: 1.0
Network:
  desc: null
  value: I3DWTrans
pretrained:
  desc: null
  value: /home/minjae/ws/MotionRGBD/Checkpoints/model_best-Nv-M.pth.tar-v1
resumelr:
  desc: null
  value: true
sample_duration:
  desc: null
  value: 64
sample_size:
  desc: null
  value: 224
grad_clip:
  desc: null
  value: 5.0
SYNC_BN:
  desc: null
  value: 1
w:
  desc: null
  value: 4
temper:
  desc: null
  value: 0.4
recoupling:
  desc: null
  value: true
knn_attention:
  desc: null
  value: 0.7
sharpness:
  desc: null
  value: true
temp:
  desc: null
  value:
  - 0.04
  - 0.07
frp:
  desc: null
  value: true
SEHeads:
  desc: null
  value: 1
N:
  desc: null
  value: 6
type:
  desc: null
  value: M
flip:
  desc: null
  value: 0.0
rotated:
  desc: null
  value: 0.5
angle:
  desc: null
  value: (-10, 10)
Blur:
  desc: null
  value: false
resize:
  desc: null
  value: (256, 256)
crop_size:
  desc: null
  value: 224
low_frames:
  desc: null
  value: 16
media_frames:
  desc: null
  value: 32
high_frames:
  desc: null
  value: 48
