common:
  data: /home/user/datasets/jester/20bn-jester-v1
  splits: /home/user/mj_ws/MotionRGBD
  #-------basic Hyparameter----------
  visdom:
    enable: False
    visname: Jester
  dataset: Jester
  batch_size: 2
  test_batch_size: 2
  num_workers: 8
  learning_rate: 0.01
  learning_rate_min: 0.00001
  momentum: 0.9
  weight_decay: 0.0003
  init_epochs: 0
  epochs: 100
  report_freq: 500
  show_cluster_result: 100
  optim: SGD
  dist: True
  vis_feature: False # Visualization?

  scheduler:
    name: cosin
    patience: 4
    warm_up_epochs: 0
  loss:
    name: CE
    labelsmooth: True
  mse_weight: 10.0
  MultiLoss: True
  loss_lamdb: [ 1, 0.5, 0.5, 0.5 ]
  distill: 1.

model:
  Network: I3DWTrans
  pretrained: '/home/minjae/ws/MotionRGBD/Checkpoints/checkpoint.pth.tar'
  # resume: ''
  resumelr: False
  sample_duration: 30
  sample_size: 224
  grad_clip: 5.
  SYNC_BN: 1
  w: 10
  temper: 0.4
  recoupling: True
  knn_attention: 0.8
  sharpness: True
  temp: [ 0.04, 0.07 ]
  frp: True
  SEHeads: 1
  N: 6

dataset:
  type: M
  flip: 0.0
  rotated: 0.5
  angle: (-10, 10)
  Blur: False
  resize: (256, 256)
  crop_size: 224
  low_frames: 16
  media_frames: 32
  high_frames: 48